{ inputs, ... }:
{
  perSystem =
    {
      pkgs,
      lib,
      ...
    }:
    let
      talos = import ./talos/default.nix { inherit pkgs lib inputs; };

      # A minimal fixture machine — used to test structural correctness
      # without needing real hardware config.
      testMachine = talos.machine {
        name = "test-node";
        version = "v1.13.3";
        sha256 = "sha256-G+f5ghwZAsY1nbXYcj4yawAIbOpBPAtfBI5ut+N6+6k=";
        schematicSha256 = "sha256-IU2M1aPO1aKFMDPV2wct734+ZNgid7g0MUDlHgsN6wQ=";
        controlPlane = false;
        tpm = {
          present = true;
        };
        disks = {
          os = {
            device = "/dev/nvme0n1";
            encrypted = true;
            provider = "nodeId";
          };
          models = {
            device = "/dev/nvme1n1";
          };
        };
        network-interfaces = {
          enp1s0 = {
            ip = "10.0.0.1";
            mac = "aa:bb:cc:dd:ee:ff";
            role = "private";
          };
          enp2s0 = {
            ip = "10.0.0.2";
            mac = "11:22:33:44:55:66";
            role = "public";
          };
        };
        nvidia = false;
        extraExtensions = [ ];
        extraPatches = [ ];
      };

      generatePatches = talos.mkGeneratePatches {
        coordinatorIp = "10.200.10.12";
        nfsPath = "/data";
      };

      # Build the DHCP hosts text and assert expected format.
      dhcpHostsText = lib.concatStringsSep "\n" testMachine.dhcpHosts;

      dhcpHostsCheck = pkgs.runCommand "check-dhcp-hosts" { } ''
        set -euo pipefail
        echo "--- DHCP hosts ---"
        printf '%s\n' ${lib.escapeShellArg dhcpHostsText}

        while IFS= read -r line; do
          [[ -z "$line" ]] && continue
          if [[ ! "$line" =~ ^([0-9a-fA-F:]{17}),([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+),(.+)$ ]]; then
            echo "FAIL: malformed dhcp-host entry: $line"
            exit 1
          fi
        done <<< ${lib.escapeShellArg dhcpHostsText}

        count=$(printf '%s\n' ${lib.escapeShellArg dhcpHostsText} | grep -c '.' || true)
        if [[ "$count" -ne 2 ]]; then
          echo "FAIL: expected 2 dhcp-host entries, got $count"
          exit 1
        fi

        cp ${pkgs.writeText "dhcp-hosts" dhcpHostsText} $out
        echo "OK: $count dhcp-host entries validated"
      '';

      imageStructureCheck = pkgs.runCommand "check-image-structure" { } ''
        set -euo pipefail

        name="${testMachine.image.name}"
        echo "Image derivation name: $name"
        if [[ "$name" != *"v1.13.3"* ]]; then
          echo "FAIL: derivation name does not include version"
          exit 1
        fi
        if [[ "$name" != *"metal-amd64"* ]]; then
          echo "FAIL: derivation name does not include platform/arch"
          exit 1
        fi
        name="${testMachine.name}"
        if [[ "$name" != *"test-node"* ]]; then
          echo "FAIL: derivation name does not have a name"
          exit 1
        fi

        echo "OK: image derivation structure looks correct"
        echo "$name" > $out
      '';

      machineConfig = testMachine.configScript;

      machineConfigCheck =
        pkgs.runCommand "check-machine-patch"
          {
            nativeBuildInputs = [ pkgs.yq-go pkgs.talosctl ];
          }
          ''
            # 1. Execute the patch generator script
            ${generatePatches}/bin/generate-patches patches/

            # Generate mock secrets for offline validation
            talosctl gen secrets -o patches/secrets.yaml

            # 2. Execute the machine config generator script
            ${machineConfig}/bin/generate-config patches/ patches/secrets.yaml

            echo "--- Machine patch YAML ---"
            # 3. Read the file generated by the previous step
            cat patches/test-node.yaml
            echo ""

            # 4. Use yq to test the generated file
            yq e '.' patches/test-node.yaml > /dev/null

            hostname=$(yq e '.machine.network.hostname' patches/test-node.yaml)
            if [[ "$hostname" != "test-node" ]]; then
              echo "FAIL: expected hostname 'test-node', got '$hostname'"
              exit 1
            fi

            echo "OK: machine patch validated"
            cp patches/test-node.yaml $out
          '';

      testMachines = talos.machines {
        control = {
          version = "v1.13.3";
          sha256 = "sha256-G+f5ghwZAsY1nbXYcj4yawAIbOpBPAtfBI5ut+N6+6k=";
          schematicSha256 = "sha256-IU2M1aPO1aKFMDPV2wct734+ZNgid7g0MUDlHgsN6wQ=";
          controlPlane = true;
          nvidia = false;
          tpm = {
            present = true;
          };
          disks = {
            os = {
              device = "/dev/nvme0n1";
              encrypted = true;
              provider = "nodeId";
            };
          };
          network-interfaces = {
            enp1s0 = {
              ip = "10.0.0.1";
              mac = "aa:bb:cc:dd:ee:ff";
              role = "private";
            };
            enp2s0 = {
              mac = "aa:bb:cc:dd:ee:fe";
              role = "disabled";
            };
          };
        };
        worker1 = {
          version = "v1.13.3";
          sha256 = "sha256-otXfOROL6Z4JdT4FGuMUGB0i0jFBXudHneBeOFCl9U8=";
          schematicSha256 = "sha256-0svhW3ksmvLqB8iNrFoIMw7QmkBGKqk3mlsXchZ+8aw=";
          controlPlane = false;
          nvidia = true;
          tpm = {
            present = true;
          };
          disks = {
            os = {
              device = "/dev/nvme0n1";
              encrypted = true;
              provider = "nodeId";
            };
            models = {
              device = "/dev/nvme1n1";
            };
          };
          network-interfaces = {
            enp1s0 = {
              ip = "10.0.0.2";
              mac = "11:22:33:44:55:66";
              role = "private";
            };
            enp2s0 = {
              ip = "10.0.0.3";
              mac = "11:22:33:44:55:67";
              role = "public";
            };
          };
        };
      };

      machinesConfigCheck =
        pkgs.runCommand "check-machines-config"
          {
            nativeBuildInputs = [ pkgs.yq-go pkgs.talosctl ];
          }
          ''
            # 1. Execute the patch generator script
            ${generatePatches}/bin/generate-patches patches/

            # Generate mock secrets for offline validation
            talosctl gen secrets -o patches/secrets.yaml

            # 2. Execute the machines config generator script
            ${testMachines.generateConfigs}/bin/generate-configs patches/ patches/secrets.yaml

            echo "--- Control machine config ---"
            cat patches/control.yaml | head -n 5
            echo "--- Worker1 machine config ---"
            cat patches/worker1.yaml | head -n 5

            [[ $(yq e '.machine.network.hostname' patches/control.yaml) == "control" ]]
            [[ $(yq e '.machine.network.hostname' patches/worker1.yaml) == "worker1" ]]

            echo "OK: machines group config validated"
            touch $out
          '';
    in
    {
      checks = {
        talos-generate-patches = generatePatches;
        talos-dhcp-hosts = dhcpHostsCheck;
        talos-image-structure = imageStructureCheck;
        talos-machine-image = testMachine.image;
        talos-machine-patch = machineConfigCheck;
        talos-machines-config = machinesConfigCheck;
      };
    };
}
